//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ExamModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Exam_MasterEntities : DbContext
    {
        public Exam_MasterEntities()
            : base("name=Exam_MasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AnswerMaster> tbl_AnswerMaster { get; set; }
        public virtual DbSet<tbl_CourseMaster> tbl_CourseMaster { get; set; }
        public virtual DbSet<tbl_DivisionMaster> tbl_DivisionMaster { get; set; }
        public virtual DbSet<tbl_Exam_Master> tbl_Exam_Master { get; set; }
        public virtual DbSet<tbl_Exam_QuestionsMaster> tbl_Exam_QuestionsMaster { get; set; }
        public virtual DbSet<tbl_ForceMaster> tbl_ForceMaster { get; set; }
        public virtual DbSet<tbl_GroupMaster> tbl_GroupMaster { get; set; }
        public virtual DbSet<tbl_MatchContentQuestionMaster> tbl_MatchContentQuestionMaster { get; set; }
        public virtual DbSet<tbl_QuestionMaster> tbl_QuestionMaster { get; set; }
        public virtual DbSet<tbl_QuestionType_Master> tbl_QuestionType_Master { get; set; }
        public virtual DbSet<tbl_Student_AnswerSheet> tbl_Student_AnswerSheet { get; set; }
        public virtual DbSet<tbl_Student_Language_Master> tbl_Student_Language_Master { get; set; }
        public virtual DbSet<tbl_Student_NCC_CourseMaster> tbl_Student_NCC_CourseMaster { get; set; }
        public virtual DbSet<tbl_Student_NCCCertificateMaster> tbl_Student_NCCCertificateMaster { get; set; }
        public virtual DbSet<tbl_Student_Qualification_Master> tbl_Student_Qualification_Master { get; set; }
        public virtual DbSet<tbl_StudentMaster> tbl_StudentMaster { get; set; }
        public virtual DbSet<tbl_Subject_master> tbl_Subject_master { get; set; }
        public virtual DbSet<tbl_User_Profile> tbl_User_Profile { get; set; }
    }
}
