//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ExamModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AttemptExamAnswerSheet
    {
        public int pkid { get; set; }
        public Nullable<int> Examid { get; set; }
        public Nullable<int> Studentid { get; set; }
        public string Question { get; set; }
        public string QuestypeName { get; set; }
        public Nullable<int> QNo { get; set; }
        public Nullable<int> QueId { get; set; }
        public string Answer1 { get; set; }
        public string Answer2 { get; set; }
        public string Answer3 { get; set; }
        public string Answer4 { get; set; }
        public Nullable<int> CorrecrtWrong { get; set; }
        public string BlanckSpace { get; set; }
        public Nullable<bool> TrueFalse { get; set; }
        public Nullable<int> CorrectAnswerDD { get; set; }
        public Nullable<int> StudentGiveAnswer { get; set; }
        public string StudentGiveAnswerfillblank { get; set; }
        public Nullable<bool> StudentGiveAnswerTrueFalse { get; set; }
        public Nullable<int> MatchAnswer { get; set; }
        public Nullable<int> StudentGiveAnswerMatch { get; set; }
        public string FullForm { get; set; }
        public string StudentZGiveAnswerFullform { get; set; }
        public Nullable<decimal> GainMarks { get; set; }
        public Nullable<decimal> QuesMarks { get; set; }
        public Nullable<System.DateTime> Addeddate { get; set; }
        public Nullable<int> QuestionStatus { get; set; }
    }
}
