//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ExamModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student_NCCCertificateMaster
    {
        public int pkid { get; set; }
        public Nullable<int> Student_fkid { get; set; }
        public string Institution { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string Certificate_Obtained { get; set; }
        public string Type_campus { get; set; }
        public Nullable<System.DateTime> AttendedYear { get; set; }
        public Nullable<System.DateTime> AppointedYear { get; set; }
        public Nullable<System.DateTime> LastModifieddate { get; set; }
    }
}
