//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ExamModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student_Language_Master
    {
        public int pkid { get; set; }
        public Nullable<int> Student_fkid { get; set; }
        public string Language { get; set; }
        public string ReadL { get; set; }
        public string Write { get; set; }
        public string Speak { get; set; }
        public string Upderstand { get; set; }
    }
}
