//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ExamModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MatchContentQuestionMaster
    {
        public int pkid { get; set; }
        public Nullable<int> Ques_fkid { get; set; }
        public string FirstColoumn { get; set; }
        public string OppositeColoumn { get; set; }
        public string AnsweColoumn { get; set; }
        public Nullable<System.DateTime> LastDatetime { get; set; }
    }
}
