//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ExamModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QuestionType_Master
    {
        public int pkid { get; set; }
        public string Questiontype { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
    }
}
