//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ExamModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student_AnswerSheet
    {
        public int pkid { get; set; }
        public Nullable<int> Student_fkid { get; set; }
        public Nullable<int> Exam_fkid { get; set; }
        public Nullable<int> Question_fkid { get; set; }
        public Nullable<int> Answer_fkid { get; set; }
        public Nullable<decimal> TotalMarks { get; set; }
        public Nullable<decimal> GainMarks { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    }
}
