//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ExamModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student_Qualification_Master
    {
        public int pkid { get; set; }
        public Nullable<int> Student_fkid { get; set; }
        public string CertificateEducation { get; set; }
        public string Subject { get; set; }
        public string Division { get; set; }
        public Nullable<System.DateTime> YearofPasswed { get; set; }
        public string Colleage { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> mid { get; set; }
        public Nullable<System.DateTime> mdate { get; set; }
    }
}
