//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ExamModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QuestionMaster
    {
        public int pkid { get; set; }
        public Nullable<int> subjecttype_fkid { get; set; }
        public string Question { get; set; }
        public string Explaination { get; set; }
        public string Subject_fkid { get; set; }
        public string hint { get; set; }
        public Nullable<decimal> Marks { get; set; }
        public Nullable<decimal> NegativeMarks { get; set; }
        public Nullable<int> SelectLevel { get; set; }
        public Nullable<System.DateTime> Adddate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> lastModified { get; set; }
    }
}
