//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ExamModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StudentMaster
    {
        public int pkid { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string mobileno { get; set; }
        public string GuardianContact { get; set; }
        public string Enrollnmentno { get; set; }
        public Nullable<int> status { get; set; }
        public string ProfilePhoto { get; set; }
        public Nullable<System.DateTime> Adddate { get; set; }
        public Nullable<System.DateTime> lastmodifieddate { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string user_fkid { get; set; }
    }
}
