//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ExamModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Stude_subjectTypeList
    {
        public int pkid { get; set; }
        public Nullable<int> stud_fkid { get; set; }
        public Nullable<int> subtype_fkid { get; set; }
        public Nullable<System.DateTime> addate { get; set; }
    }
}
