//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ExamModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student_NCC_CourseMaster
    {
        public int pkid { get; set; }
        public Nullable<int> Student_fkid { get; set; }
        public string CourseName { get; set; }
        public string TrainingInstitution { get; set; }
        public string TotalDuration { get; set; }
        public Nullable<System.DateTime> DurationFromDate { get; set; }
        public Nullable<System.DateTime> DurationToDate { get; set; }
        public string Grading { get; set; }
        public Nullable<bool> CheckRTU { get; set; }
        public string RTUReason { get; set; }
    }
}
